In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
gdf = gpd.read_file('../burkolas_v3/adatok/osszekapcsolt_pontok_es_cimek.gpkg')

In [3]:
gdf

,szavazokorid,utca,hazszam,telepules,geometry
0,1600517,Petőfi Sándor utca,1,Ibafa,POINT (17.91557 46.15492)
1,1600517,Petőfi Sándor utca,10,Ibafa,POINT (17.91403 46.15501)
2,1600517,Petőfi Sándor utca,11,Ibafa,POINT (17.91308 46.15513)
3,1600517,Petőfi Sándor utca,12,Ibafa,POINT (17.91349 46.15506)
4,1600517,Petőfi Sándor utca,14,Ibafa,POINT (17.91289 46.15508)
...,...,...,...,...,...
1568296,1610605,Lőrinc utca,14,Szentes,POINT (20.24952 46.64169)
1568297,1610605,Farkas zug,2,Szentes,POINT (20.24908 46.6472)
1568298,1610607,Kötő utca,1,Szentes,POINT (20.25879 46.64286)
1568299,1610615,Bacsó Béla utca,9-13,Szentes,POINT (20.26236 46.65027)
1568300,1610615,Bacsó Béla utca,15,Szentes,POINT (20.26262 46.64949)

In [4]:
varosok = gdf['telepules'].unique().tolist()

In [6]:
len(varosok)

2846

In [8]:
gdf.query('telepules == "12. kerület"')

Empty GeoDataFrame
Columns: [szavazokorid, utca, hazszam, telepules, geometry]
Index: []