In [2]:
import pandas as pd

In [5]:
df = pd.read_parquet('../data/work_data/teljes_ms_google_tisztott.parquet')

In [6]:
df.head()

,gid,utca,cim,telepules,iszam,orszag,geometry
0,47289911900891,Csalitos utca,6,Tököl,2316,Hungary,b'\x01\x01\x00\x00\x00\x17\x1eE\xe7F\x023@!\xd...
1,47290591901043,Diana sétány,55,Tököl,2316,Hungary,b'\x01\x01\x00\x00\x00\xbd3\x7f\xf1\xb1\x023@F...
2,47289711900922,Diana sétány,71,Tököl,2316,Hungary,b'\x01\x01\x00\x00\x00\x83.\xe1\xd0[\x023@\xd6...
3,47290281900996,Diana sétány,61,Tököl,2316,Hungary,"b""\x01\x01\x00\x00\x00\xf8jGq\x8e\x023@\xb0eCH..."
4,47283961900063,Diana sétány,147,Tököl,2316,Hungary,b'\x01\x01\x00\x00\x00\xc4\xd1\xb0s.\x003@\xbc...

In [ ]:
df = pd.read_parquet('../data/work_data/osm_cim_kordinata.parquet')

In [8]:
df

,id,geometry,addr:city,addr:postcode,addr:street,addr:housenumber
0,node/16947670,"b'\x01\x01\x00\x00\x00""u\x96\xb4=#2@\xd5\x98k,...",Orfű,7677,Dollár út,1
1,node/25546152,b'\x01\x01\x00\x00\x005B?S\xaf92@*\xca\x00\xab...,Pécs,7623,Indóház tér,1
2,node/33123162,b'\x01\x01\x00\x00\x008;\x08\xf0\xcc\x8e1@L\xe...,Fonyód,8640,Ady Endre utca,2
3,node/33127897,b'\x01\x01\x00\x00\x00nP\xfb\xad\x9d\n2@p\x92\...,Tab,8660,Kossuth Lajos utca,1
4,node/94743595,b'\x01\x01\x00\x00\x00\x9a\x8d\xdf%\x82N1@`P\x...,Somogyszob,7563,Keleti köz,1
...,...,...,...,...,...,...
681195,relation/19340426,"b'\x01\x01\x00\x00\x00m""\xed8\x08\xa35@\x1e\x0...",Debrecen,4028,Táncsics Mihály utca,7-15
681196,relation/19716998,b'\x01\x01\x00\x00\x00\xb5\xb7\x93\xdd\xb906@A...,Nyírmada,4564,Ady Endre út,16
681197,relation/20047599,b'\x01\x01\x00\x00\x00\xbaO\xa6\x9dP24@h\xc0h\...,Szolnok,5000,Kossuth tér,4
681198,relation/20081016,b'\x01\x01\x00\x00\x00r\xa5\xc0\xc5\xf5\xab5@\...,Debrecen,4033,Veres Péter utca,77
681199,relation/20156689,b'\x01\x01\x00\x00\x00\x18\xfe\xf7ZN\x995@\xad...,Debrecen,4002,Vértesi utca,1-3

In [9]:
df = pd.read_parquet('../data/work_data/osm_gmaps_merged.parquet')

In [10]:
df

,geometry,city,postcode,street,housenumber,source,color
0,"b'\x01\x01\x00\x00\x00""u\x96\xb4=#2@\xd5\x98k,...",Orfű,7677,Dollár út,1,osm,#d95f02
1,b'\x01\x01\x00\x00\x005B?S\xaf92@*\xca\x00\xab...,Pécs,7623,Indóház tér,1,osm,#d95f02
2,b'\x01\x01\x00\x00\x008;\x08\xf0\xcc\x8e1@L\xe...,Fonyód,8640,Ady Endre utca,2,osm,#d95f02
3,b'\x01\x01\x00\x00\x00nP\xfb\xad\x9d\n2@p\x92\...,Tab,8660,Kossuth Lajos utca,1,osm,#d95f02
4,b'\x01\x01\x00\x00\x00\x9a\x8d\xdf%\x82N1@`P\x...,Somogyszob,7563,Keleti köz,1,osm,#d95f02
...,...,...,...,...,...,...,...
2511551,b'\x01\x01\x00\x00\x00\xe9z\xa2\xeb\xc2\xe33@8...,Atkár,3213,Bajcsy-Zsilinszky út,14,gmaps,#1b9e77
2511552,b'\x01\x01\x00\x00\x00\xed:e\x7f\xea\x076@\x8d...,Dámóc,3978,Fő utca,102,gmaps,#1b9e77
2511553,b'\x01\x01\x00\x00\x00\x91\x83m\x1fM\xc03@\xe8...,Kiskunmajsa,6120,Fő utca,181,gmaps,#1b9e77
2511554,"b'\x01\x01\x00\x00\x00x\x82X\x91,\x913@\xf1\xa...",Tápiószecső,2251,Bartók Béla utca,7,gmaps,#1b9e77
2511555,b'\x01\x01\x00\x00\x00\xb32\xd0k\xa2\x9b4@}2\x...,Magyarcsanád,6932,Petőfi Sándor utca,7,gmaps,#1b9e77

In [21]:
df = pd.read_csv('../data/nyers_data/valasztas_cimek_2022.csv')

In [34]:
df[df['telepules_nev'].str.contains('Budapest')]

,szavazokor_id,utca_id,utca_nev,hazszam,telepules_id,telepules_nev
1047,1600526,1332616,Nőegylet utca,2,734,Budapest I. kerület
1048,1600526,1332590,Kapisztrán tér,000002-0004,734,Budapest I. kerület
1049,1600526,1332590,Kapisztrán tér,1,734,Budapest I. kerület
1050,1600526,1332645,Szentháromság utca,000004-0006,734,Budapest I. kerület
1051,1600526,1332645,Szentháromság utca,000009-0011,734,Budapest I. kerület
...,...,...,...,...,...,...
3449251,1610428,1331663,Muskétás utca,1,1189,Budapest XI. kerület
3449252,1610428,1331663,Muskétás utca,1,1189,Budapest XI. kerület
3449253,1610428,1331613,Kékperje utca,4,1189,Budapest XI. kerület
3449254,1610428,1331613,Kékperje utca,6,1189,Budapest XI. kerület
3449255,1610428,1331613,Kékperje utca,8,1189,Budapest XI. kerület

In [42]:
df.query('telepules_nev == "Sajószentpéter"')

Empty DataFrame
Columns: [szavazokor_id, utca_id, utca_nev, hazszam, telepules_id, telepules_nev]
Index: []

In [43]:
df[df['telepules_nev'].str.contains('Sajószentpéter')]

Empty DataFrame
Columns: [szavazokor_id, utca_id, utca_nev, hazszam, telepules_id, telepules_nev]
Index: []